name: Build and Deploy Next.js to SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Create deployment package
        run: |
          cd out
          zip -r ../bible-annals-deploy.zip . -x "*.DS_Store" "*.log"
          cd ..

      - name: Upload deployment package via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './bible-annals-deploy.zip'
          remote_path: '/home/${{ secrets.SFTP_USERNAME }}/uploads/'
          sftpArgs: '-o ConnectTimeout=5'
          sftp_only: true
          delete_remote_files: false
        
      - name: Unzip and publish site
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          script: |
            timestamp=$(date +%Y%m%d-%H%M%S)
            echo "Creating deployment directory: $timestamp"
            mkdir "$timestamp"
            
            echo "Unzipping deployment package..."
            unzip -o uploads/bible-annals-deploy.zip -d "$timestamp/"
            
            echo "Cleaning up zip file..."
            rm uploads/bible-annals-deploy.zip
            
            echo "Updating symlink to new deployment..."
            ln -snf "$timestamp" bibleannals.com
            
            echo "Deployment completed successfully!"
            ls -la bibleannals.com
