name: Build and Deploy Next.js to SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build # or your build command

      - name: Copy files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './out/*'
          remote_path: 'uploads/'
          sftpArgs: '-o ConnectTimeout=5'
        
      - name: Publish site
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          script: |
            timestamp=$(date +%Y%m%d-%H%M%S)
            echo "Created $timestamp"
            mkdir "$timestamp"
            mv uploads/* "$timestamp/"
            ln -snf "$timestamp" bibleannals.com
            echo "Deployment completed at $(date)" >> /var/log/deployments.log
